baseURL = "https://viaops.com/"
languageCode = "en-us"
title = "ViaOps"
theme = "hyde-hyde"
googleAnalytics = "UA-162103303-1"

summarylength = 30
paginate = 5

[params]
    author = "viaops"
    description = "DevOps/SRE Incubator"
    authorimage = "/images/profile.png"
    highlightjs = true
    highlightjsstyle = "dracula"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[params.social]
    github = "<viaops>"
    linkedin = "viaops"
    twitter = "viaops"
    facebook = "viaops"
    stackoverflow = "viaops"
    telegram = "viaops"
    email = "mail@viaops.com"
