baseURL = "https://www.viaops.com/"
languageCode = "en-us"
title = "ViaOps"
theme = "minimal"
disqusShortname = "viaops" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "viaops"
    description = "DevOps/SRE Incubator"
    githubUsername = "viaops"
    accent = "blue"
    showBorder = false
    backgroundColor = "white"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "dracula"
    highlightLanguages = ["go", "python", "bash", "javascript", "ruby"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mail@viaops.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/viaops/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/viaops/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/viaops/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/viaops/"
    name = "stack-overflow"
    weight = 5
